server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # 反向代理 API 请求到后端容器
    location /v1 {
        proxy_pass http://shareflow-api-overseas:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Vue Router history 模式支持
    location / {
        try_files $uri $uri/ /index.html;
    }
}
